#!/usr/bin/env ruby
# frozen_string_literal: true

require 'expectacle'
require 'optparse'
require 'yaml'

option = {}
opt = OptionParser.new
opt.on('-h', '--hosts=FILE', 'Host list file') do |value|
  option[:hosts] = value
end
opt.on('-c', '--commands=FILE', 'Command list file') do |value|
  option[:commands] = value
end
opt.on('-b', '--base-dir=DIR', 'Base directory path') do |value|
  option[:base_dir] = value
end
opt.on('-p', '--preview', 'Preview parameter') do |value|
  option[:preview] = value
end
opt.on('-r', '--run', 'Run(exec) commands to each hosts') do |value|
  option[:run] = value
end
opt.parse!(ARGV)

file_dir = File.dirname(File.expand_path(__FILE__))
base_dir = if option.key?(:base_dir)
             option[:base_dir]
           else
             File.expand_path('../vendor', file_dir)
           end
thrower = Expectacle::Thrower.new(base_dir: base_dir)

hosts = YAML.load_file(File.join(thrower.hosts_dir, option[:hosts]))
commands = YAML.load_file(File.join(thrower.commands_dir, option[:commands]))
if option[:preview]
  thrower.preview_parameter(hosts, commands)
elsif option[:run]
  thrower.run_command_for_all_hosts(hosts, commands)
else
  STDERR.puts "#{$PROGRAM_NAME}: Action(preview/run) did not specified."
end
